# Generated by Django 4.2.4 on 2023-09-25 07:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0002_product_product_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='reported_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_banned', models.BooleanField(default=False)),
                ('reported_at', models.DateField(auto_now_add=True)),
                ('Product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
