# Generated by Django 4.2.4 on 2023-09-25 07:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0003_reported_product'),
        ('order', '0002_returnedorder'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReturnedOrder',
            new_name='ReturnOrder',
        ),
    ]
